[project]
name = "famigo-ui"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.12.0.88",
    "streamlit>=1.48.1",
    "watchdog>=6.0.0",
]
